name: Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v1
      
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - name: 'npm install and build'
      run: |
        npm install
        cd frontend/my-app && npm install && cd ../../
        npm run build
        cd frontend/my-app && rm -rf node_modules/ && cd ../../
        
    - name: Run Azure webapp deploy using publish profile
      uses: azure/webapps-deploy@v1
      with:
        app-name: fullhouse-app
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
